# Generated by Django 4.0.4 on 2022-06-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSupplier', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('lamaKontrak', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='idSupplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventaris.supplier'),
        ),
    ]
