# Generated by Django 4.0.4 on 2022-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_rename_hargabeli_barang_harga_beli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='img_produk',
            field=models.ImageField(null=True, upload_to='img_produk/'),
        ),
        migrations.AddField(
            model_name='barang',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
